type1: 1
type2: 1
type3: 1
r12Min: 1.0
r12Max: 4.0
r12Count: 20
r13Min: 1.0
r13Max: 4.0
r13Count: 20
angleMin: 1.0	  # to avoid problems with convergence in HF
angleMax: 3.14159 # = pi
angleCount: 20
basisName: "6-31Gds"
groundState: {
    r12: 3.5,
    r13: 3.5,
    angle: 0.4496
}
