atoms: [
    {
        type: "C",
        basis: "6-311++G**",
        position: [0,0,0]
    },
    {
        type: "H",
        basis: "6-311++G**",
        position: [1,0,0]
    },
    {
        type: "H",
        basis: "6-311++G**",
        position: [-1,0,0]
    },
    {
        type: "H",
        basis: "6-311++G**",
        position: [0,1,0]
    },
    {
        type: "H",
        basis: "6-311++G**",
        position: [0,-1,0]
    }
]
method: "unrestricted"
output: ["energy"]
