description: "CH4 molecule with angle approx. 109.45 deg and bond length approx. 2.11 a0"
angle: 1.910268
bondLength: 1.118
atoms: [
    {
        type: "C",
        position: [0,0,0]
    },
    {
        type: "H",
        position: [ 1.67381799,  0.        , -1.18356805]
    },
    {
        type: "H",
        position: [-1.67381799,  0.        , -1.18356805]
    },
    {
        type: "H",
        position: [ 0.        ,  1.67381799,  1.18356805]
    },
    {
        type: "H",
        position: [ 0.        , -1.67381799,  1.18356805]
    }
]
basis: "3-21G"
method: "unrestricted"
output: ["energy", "density", "electrostatic_potential"]
