atoms: [
    {
        type: "C",
        position: [0,0,0]
    },
    {
        type: "O",
        position: [-2.19208,0,0]
    },
    {
        type: "O",
        position: [2.19208,0,0]
    }
]
basis: "6-311++G**"
method: "unrestricted"
output: ["energy"]
