atoms: [
    {
        type: "F",
        position: [0,0,0]
    },
    {
        type: "H",
        position: [1.733,0,0]
    }
]
basis: "6-311++G**"
method: "unrestricted"
output: ["energy", "electrostatic_potential"]
