atoms: [
    {
        type: "F",
        position: [0,0,0]
    },
    {
        type: "H",
        position: [1.733,0,0]
    }
]
basis: "3-21G"
method: "unrestricted"
output: ["energy", "density", "electrostatic_potential"]
