atoms: [
    {
        type: "H",
        position: [-3,0,0]
    },
    {
        type: "H",
        position: [3,0,0]
    }
]
basis: "6-311++G**"
method: "unrestricted"
output: ["energy", "density"]
