description: "Water molecule, H2O"
atoms: [
    {
        type: "O",
        position: [0,0,0]
    },
    {
        type: "H",
        position: [1.7970, 0, 0]
    },
    {
        type: "H",
        position: [-0.448, 1.740, 0]
    }
]
basis: "3-21G"
method: "unrestricted"
#output: ["energy", "density"]
output: ["energy", "density", "electrostatic_potential"]
