description: "Water molecule, H2O"
atoms: [
    {
        type: "O",
        basis: "6-311++G**",
        position: [0,0,0]
    },
    {
        type: "H",
        basis: "6-311++G**",
        position: [1.7970, 0, 0]
    },
    {
        type: "H",
        basis: "6-311++G**",
        position: [-0.448, 1.740, 0]
    }
]
method: "unrestricted"
output: ["energy"]
