atoms: [
    {
        type: "O",
        position: [0,0,0]
    },
    {
        type: "O",
        position: [2.282,0,0]
    }
]
basis: "6-311++G**"
method: "unrestricted"
output: ["energy"]
electronsDown: 9
