atoms: [
    {
        type: "O",
        position: [0,0,0]
    },
    {
        type: "O",
        position: [2.282,0,0]
    }
]
basis: "3-21G"
method: "unrestricted"
output: ["energy", "density", "electrostatic_potential"]
electronsDown: 9
